services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: m-tix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome1!
    ports:
      - "5433:5432"
    volumes:
      - m_tix_volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"
    volumes:
      - minio_volume:/data

volumes:
  m_tix_volume:
  minio_volume:
