-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE booking_id_seq;

CREATE SEQUENCE booking_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE city_id_seq;

CREATE SEQUENCE city_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE movie_id_seq;

CREATE SEQUENCE movie_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE schedule_id_seq;

CREATE SEQUENCE schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE seat_id_seq;

CREATE SEQUENCE seat_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE seat_type_id_seq;

CREATE SEQUENCE seat_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE studio_id_seq;

CREATE SEQUENCE studio_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE studio_type_id_seq;

CREATE SEQUENCE studio_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE theater_id_seq;

CREATE SEQUENCE theater_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE users_id_seq;

CREATE SEQUENCE users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.city definition

-- Drop table

-- DROP TABLE city;

CREATE TABLE city (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT city_pkey PRIMARY KEY (id)
);


-- public.movie definition

-- Drop table

-- DROP TABLE movie;

CREATE TABLE movie (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	duration int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	showing_start_date timestamp(6) NULL,
	synopsis text NOT NULL,
	traileruri varchar(255) NOT NULL,
	showing_end_date timestamp(6) NULL,
	imageuri varchar(255) NULL,
	CONSTRAINT movie_pkey PRIMARY KEY (id)
);


-- public.seat_type definition

-- Drop table

-- DROP TABLE seat_type;

CREATE TABLE seat_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	additional_price numeric(38, 2) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT seat_type_pkey PRIMARY KEY (id)
);


-- public.studio_type definition

-- Drop table

-- DROP TABLE studio_type;

CREATE TABLE studio_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	column_size int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	row_size int4 NOT NULL,
	CONSTRAINT studio_type_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE users;

CREATE TABLE users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone_no varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.theater definition

-- Drop table

-- DROP TABLE theater;

CREATE TABLE theater (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	city_id int8 NULL,
	CONSTRAINT theater_pkey PRIMARY KEY (id),
	CONSTRAINT fkikchmxlrjeeyokbkoaijxgycm FOREIGN KEY (city_id) REFERENCES city(id)
);


-- public.studio definition

-- Drop table

-- DROP TABLE studio;

CREATE TABLE studio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	studio_type_id int8 NULL,
	theater_id int8 NULL,
	CONSTRAINT studio_pkey PRIMARY KEY (id),
	CONSTRAINT fk13x8lca6psy4u4jjb5uodl5el FOREIGN KEY (studio_type_id) REFERENCES studio_type(id),
	CONSTRAINT fkjbpjoovf53kk4g2xct2h454dm FOREIGN KEY (theater_id) REFERENCES theater(id)
);


-- public.schedule definition

-- Drop table

-- DROP TABLE schedule;

CREATE TABLE schedule (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	end_show_time timestamp(6) NULL,
	price numeric(38, 2) NOT NULL,
	show_time timestamp(6) NULL,
	movie_id int8 NULL,
	studio_id int8 NULL,
	CONSTRAINT schedule_pkey PRIMARY KEY (id),
	CONSTRAINT fka6hosaihwhtb3scvamdyh9mlv FOREIGN KEY (movie_id) REFERENCES movie(id),
	CONSTRAINT fki0lda4gvpvspv1cywe9skv40m FOREIGN KEY (studio_id) REFERENCES studio(id)
);


-- public.seat definition

-- Drop table

-- DROP TABLE seat;

CREATE TABLE seat (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	column_index int4 NOT NULL,
	is_available bool NULL,
	is_visible bool NULL,
	row_index int4 NOT NULL,
	seat_number varchar(255) NOT NULL,
	seat_type_id int8 NULL,
	studio_id int8 NULL,
	CONSTRAINT seat_pkey PRIMARY KEY (id),
	CONSTRAINT fkd4mx49q62bd2apkk2rfkl8l9w FOREIGN KEY (seat_type_id) REFERENCES seat_type(id),
	CONSTRAINT fkoi5aylqkf8y4nqj3c8rndsfjt FOREIGN KEY (studio_id) REFERENCES studio(id)
);


-- public.booking definition

-- Drop table

-- DROP TABLE booking;

CREATE TABLE booking (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	booking_status_enum varchar(255) NOT NULL,
	is_paid bool NULL,
	order_date timestamp(6) NULL,
	paid_date timestamp(6) NULL,
	total_price numeric(38, 2) NOT NULL,
	schedule_id int8 NULL,
	user_id int8 NULL,
	expired_date timestamp(6) NULL,
	CONSTRAINT booking_booking_status_enum_check CHECK (((booking_status_enum)::text = ANY ((ARRAY['PAID'::character varying, 'WAITING'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT booking_pkey PRIMARY KEY (id),
	CONSTRAINT fk7udbel7q86k041591kj6lfmvw FOREIGN KEY (user_id) REFERENCES users(id),
	CONSTRAINT fkdkador5s62nuvhdf672u65fs9 FOREIGN KEY (schedule_id) REFERENCES schedule(id)
);


-- public.booking_seat definition

-- Drop table

-- DROP TABLE booking_seat;

CREATE TABLE booking_seat (
	booking_id int8 NOT NULL,
	seat_id int8 NOT NULL,
	CONSTRAINT booking_seat_pkey PRIMARY KEY (booking_id, seat_id),
	CONSTRAINT fk3gcy7w2me25kc4qp8nobmg4q6 FOREIGN KEY (booking_id) REFERENCES booking(id),
	CONSTRAINT fk3y806wtfhomwvu02t1u7u2136 FOREIGN KEY (seat_id) REFERENCES seat(id)
);