-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

COMMENT ON SCHEMA public IS 'standard public schema';

-- DROP SEQUENCE public.booking_id_seq;

CREATE SEQUENCE public.booking_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.city_id_seq;

CREATE SEQUENCE public.city_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.movie_id_seq;

CREATE SEQUENCE public.movie_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.schedule_id_seq;

CREATE SEQUENCE public.schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.seat_id_seq;

CREATE SEQUENCE public.seat_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.seat_type_id_seq;

CREATE SEQUENCE public.seat_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.studio_id_seq;

CREATE SEQUENCE public.studio_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.studio_type_id_seq;

CREATE SEQUENCE public.studio_type_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.theater_id_seq;

CREATE SEQUENCE public.theater_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- public.city definition

-- Drop table

-- DROP TABLE public.city;

CREATE TABLE public.city (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT city_pkey PRIMARY KEY (id)
);


-- public.movie definition

-- Drop table

-- DROP TABLE public.movie;

CREATE TABLE public.movie (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	duration int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	showing_start_date timestamp(6) NULL,
	synopsis text NOT NULL,
	traileruri varchar(255) NOT NULL,
	CONSTRAINT movie_pkey PRIMARY KEY (id)
);


-- public.seat_type definition

-- Drop table

-- DROP TABLE public.seat_type;

CREATE TABLE public.seat_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	additional_price numeric(38, 2) NULL,
	"name" varchar(255) NOT NULL,
	CONSTRAINT seat_type_pkey PRIMARY KEY (id)
);


-- public.studio_type definition

-- Drop table

-- DROP TABLE public.studio_type;

CREATE TABLE public.studio_type (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	column_size int4 NOT NULL,
	"name" varchar(255) NOT NULL,
	row_size int4 NOT NULL,
	CONSTRAINT studio_type_pkey PRIMARY KEY (id)
);


-- public.users definition

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	email varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	phone_no varchar(255) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


-- public.theater definition

-- Drop table

-- DROP TABLE public.theater;

CREATE TABLE public.theater (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	city_id int8 NULL,
	CONSTRAINT theater_pkey PRIMARY KEY (id),
	CONSTRAINT fkikchmxlrjeeyokbkoaijxgycm FOREIGN KEY (city_id) REFERENCES public.city(id)
);


-- public.studio definition

-- Drop table

-- DROP TABLE public.studio;

CREATE TABLE public.studio (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	studio_type_id int8 NULL,
	theater_id int8 NULL,
	CONSTRAINT studio_pkey PRIMARY KEY (id),
	CONSTRAINT fk13x8lca6psy4u4jjb5uodl5el FOREIGN KEY (studio_type_id) REFERENCES public.studio_type(id),
	CONSTRAINT fkjbpjoovf53kk4g2xct2h454dm FOREIGN KEY (theater_id) REFERENCES public.theater(id)
);


-- public.schedule definition

-- Drop table

-- DROP TABLE public.schedule;

CREATE TABLE public.schedule (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	end_show_time timestamp(6) NULL,
	price numeric(38, 2) NOT NULL,
	show_time timestamp(6) NULL,
	movie_id int8 NULL,
	studio_id int8 NULL,
	CONSTRAINT schedule_pkey PRIMARY KEY (id),
	CONSTRAINT fka6hosaihwhtb3scvamdyh9mlv FOREIGN KEY (movie_id) REFERENCES public.movie(id),
	CONSTRAINT fki0lda4gvpvspv1cywe9skv40m FOREIGN KEY (studio_id) REFERENCES public.studio(id)
);


-- public.seat definition

-- Drop table

-- DROP TABLE public.seat;

CREATE TABLE public.seat (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	colum_index int4 NOT NULL,
	is_available bool NULL,
	is_visible bool NULL,
	row_index int4 NOT NULL,
	seat_number varchar(255) NOT NULL,
	seat_type_id int8 NULL,
	studio_id int8 NULL,
	CONSTRAINT seat_pkey PRIMARY KEY (id),
	CONSTRAINT fkd4mx49q62bd2apkk2rfkl8l9w FOREIGN KEY (seat_type_id) REFERENCES public.seat_type(id),
	CONSTRAINT fkoi5aylqkf8y4nqj3c8rndsfjt FOREIGN KEY (studio_id) REFERENCES public.studio(id)
);


-- public.booking definition

-- Drop table

-- DROP TABLE public.booking;

CREATE TABLE public.booking (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	booking_status_enum varchar(255) NOT NULL,
	is_paid bool NULL,
	order_date timestamp(6) NULL,
	paid_date timestamp(6) NULL,
	total_price numeric(38, 2) NOT NULL,
	schedule_id int8 NULL,
	user_id int8 NULL,
	CONSTRAINT booking_booking_status_enum_check CHECK (((booking_status_enum)::text = ANY ((ARRAY['PAID'::character varying, 'WAITING'::character varying, 'CANCELLED'::character varying])::text[]))),
	CONSTRAINT booking_pkey PRIMARY KEY (id),
	CONSTRAINT fk7udbel7q86k041591kj6lfmvw FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkdkador5s62nuvhdf672u65fs9 FOREIGN KEY (schedule_id) REFERENCES public.schedule(id)
);


-- public.booking_seat definition

-- Drop table

-- DROP TABLE public.booking_seat;

CREATE TABLE public.booking_seat (
	booking_id int8 NOT NULL,
	seat_id int8 NOT NULL,
	CONSTRAINT booking_seat_pkey PRIMARY KEY (booking_id, seat_id),
	CONSTRAINT fk3gcy7w2me25kc4qp8nobmg4q6 FOREIGN KEY (booking_id) REFERENCES public.booking(id),
	CONSTRAINT fk3y806wtfhomwvu02t1u7u2136 FOREIGN KEY (seat_id) REFERENCES public.seat(id)
);